### ISSUE TITLE
ripple

### ISSUE THREAD

**Issue by razerblackwidow** [1kc/razer-macos#132]
You should add the ripple effect for the razer blackwidow 2019 or for all of the keyboards it would be awesome.

**Comment by dhobi** [comment]
I think the main issue with the ripple effect is that it is custom made while other effects like breath, wave, spectrum have a reserved usb control message. Checking openrazer, Ripple is implemented by reading the pressed key, calculating the circle and just highlight keys which or on the line of the circle. The circle gets bigger the more time passed by since the click.
For razer macos, we would need to:
- listen for key presses
- make sure we already support custom frame writes
- port the ripple effect code to...javascript? I guess workers (if supported in electron) could do this just fine.

Any other thoughts?

**Comment by akaler** [comment]
Can we just use python to port it to razer-macos? Which might be easier since openrazer uses python

**Comment by 1kc** [comment]
That means we have run python code from node? Or have some sort of python background process we have to communicate with.

On 31 Dec 2020, at 9:33 am, Abhijot Kaler <notifications@github.com> wrote:

﻿

Can we just use python to port it to razer-macos? Which might be easier since openrazer uses python

**Comment by dhobi** [comment]
Even if it sounds tempting to reuse already existing code, I fear mainly two things:
1. the additional complexity of integrating and communicating with Python.
2. the code we want to reuse has most likely to be adapted/changed as well.

**Comment by dhobi** [comment]
Ripple has been added. Thanks again @stevenliuyi
