### ISSUE TITLE
Starlight Custom Dual Color on Huntsman Elite

### ISSUE THREAD

**Issue by brasky05** [1kc/razer-macos#172]
First of all let me express my gratitude to this community for making my Keyboard/Mouse infinitely more functional.  I am very appreciative.  I just downloaded the latest release and when I tried to use the custom custom dual color I ran into an error, that I thought you would want to know about.:

Uncaught Exception:
TypeError: Cannot read property 'r' of undefined
    at click (/Applications/Razer macOS.app/Contents/Resources/app.asar/webpack:/src/main/index.js:673:39)
    at MenuItem.click (electron/js2c/browser_init.js:1549:9)
    at Function.executeCommand (electron/js2c/browser_init.js:1810:13)

In the meantime I will happily use all of the awesome new functionality that you have made available.  Thanks again!

**Comment by 1kc** [comment]
Thanks for this report. I'll try to fix it tmr

**Comment by Stanman04** [comment]
that doesn't need to be fixed,
you just didn't set the secondary custom color which is why you got that error message, I tried it out, and got the same message the first time because the secondary color wasn't set. As soon as I set that, It worked perfectly.

Unfortunately though, wave speed still doesn't work on the Ornata v2.


Thank you sooo much for this program!!!

**Comment by brasky05** [comment]
Oops I stand corrected.  I didnt see the option to set a secondary color and assumed that the custom colors would just pick the first 2 I had set as primary.  My mistake.  Thanks again.  Works great!

**Comment by 1kc** [comment]
Should be fixed now
