### ISSUE TITLE
Support for multiple devices

### ISSUE THREAD

**Issue by alexargo** [1kc/razer-macos#2]
I've got three Razer devices connected to my Mac, but it seems hardcoded for one device right now. (I have a keyboard, Mouse, and Speakers). Sometimes when I start the app up, it recognizes my keyboard and I can control the implemented things. Sometimes it just says "Unrecognized Device".

**Comment by 1kc** [comment]
Thanks for opening the issue. 
Yes, multiple device support has not been added, since only keyboard support has been implemented.
Adding other peripheral types would require porting:
https://github.com/openrazer/openrazer/blob/master/driver/razermouse_driver.c
etc.
Could I also ask how well does you keyboard work? What model is it?

**Comment by alexargo** [comment]
I've got a Razer BlackWidow Elite. None/Static White/Wave all seem to work perfectly. The rest just seem to do something similar to the "Spectrum" effect where it cycles through colors.

The reason I added this, was because while I was developing I launched the app and "Unrecognized Device" even though I had one keyboard plugged in. It didn't seem to be filtering out my mouse/speakers. I'll try and take a look and figure out if I can get it to happen again. Maybe for now, it just needs to filter out any device that isn't a keyboard? I've been hopping around looking for projects like this and so far, this is the simplest one that I have found and seems very straightforward to build. Looking forward to contributing more. Would love to make all of my peripherals work when my KVM is set to my Mac.

**Comment by 1kc** [comment]
It's great that those are working on your keyboard! The reason that the other colours are not working is because they are yet to be implemented. Adding the new colours shouldn't be a challenge since it just involves mapping functions in src/driver/razerkbd_driver.c to calls in src/driver/addon.cc. As of now, it filters all Razer devices so this will need to be change to be just keyboards. Looking to put some time into it over the weekend.

I look forward too. openrazer is the upstream project which provides wide a range of Razer drivers for Linux, some driver code can be directly pulled from that project. Let me know if you need help navigating through the codebase.

The plan is to support all peripherals. I don't think this is too ambitious given that openrazer supports virtually every Razer device.

**Comment by 1kc** [comment]
Filtering only keyboards has been added.

**Comment by hrytskivr** [comment]
Any way I can help on this? I'm a full-stack (js, c#) developer. I'd be really interested in multiple devices support.

**Comment by 1kc** [comment]
> Any way I can help on this? I'm a full-stack (js, c#) developer. I'd be really interested in multiple devices support.

Sounds great. The two key things are porting the C drivers over from openrazer and updating the front-end. The front-end is written in Electron/React, we could come up with some ideas on what the UI could look like?

There is an issue open here for mouse support.
https://github.com/1kc/razer-macos/issues/12

**Comment by sebmck** [comment]
@1kc Is multiple device support a limitation of the frontend or the C driver?

**Comment by 1kc** [comment]
Parts of the C driver has to be rewritten to handle multiple devices, currently it only filters out the keyboard. I did some testing on the 'mouse' branch and it seems to be able to pick up the mouse. 
![Screen Shot 2020-05-15 at 5 28 27 pm](https://user-images.githubusercontent.com/20840688/82023401-9461f380-96d1-11ea-951c-ce9870e21bea.png)
Aside from getting the device name, the other features are yet to be implemented for mouse.

Guess we could look at how to implement the Electron UI for switching between mouse and keyboard?

**Comment by alexargo** [comment]
Hey. Just noticed you did a mouse release! It's does not support my mouse specifically, but it seems like you have some type of support for multiple devices. Seems like this is probably good to close unless you think whatever support is not robust @1kc

**Comment by 1kc** [comment]
Hey @alexargo, what mouse do you have?

**Comment by alexargo** [comment]
It's a Razer Mamba Hyperflux. The deviceID I see listed in my device System Report is listed as "Razer Firefly Hyperflux | 1532:0068" on the openrazr page which seems to be implemented in https://github.com/openrazer/openrazer/blob/master/driver/razermousemat_driver.c

... It's a weird guy. And I'm not sure if that just control the mousepad or if it also controls the mouse itself or just the mousepad. It's one USB cable that plugs both devices in (the Razer Firefly Hyperflux charges a small battery in the mouse)

**Comment by alexargo** [comment]
I'd say there is support for multiple devices at this points... it's all about whether a specific device type is supported. Luckily My mouse and keyboard(Razer BlackWidow Elite) are both supported now.

My mouse + mousemat is now showing up as "Razer Firefly Hyperflux" and I can control it perfectly (even working on Big Sur) except for the "Wave" support. I'm going to call it good though.
