### ISSUE TITLE
Razer Huntsman Elite has slower spectrum cycling

### ISSUE THREAD

**Issue by QuantumBytes95** [1kc/razer-macos#290]
When I am trying to do spectrum cycling on all devices, my Razer Huntsman Elite is always slower than the rest of my devices. They all start out with the same colour but the Razer Huntsman Elite is not able to keep up with the speed of the cycle. This wasn't an issue with the previous 0.3.6 build and Synapse 3 on Windows. Curious to see if this is happening to anyone else.

**Comment by dhobi** [comment]
I see, sorry, that was me. I changed it to individual spectrum commands for each device not realizing (because it worked so nicely with my setup) that devices could have different cycling speeds. I'll see to add back the Spectrum (Animation) to the main menu so that we will have both options. Until then 0.3.6 is your version. ☹️

**Comment by QuantumBytes95** [comment]
Not a problem! Thanks for the quick reply!

**Comment by dhobi** [comment]
This should be fixed now with the latest release 0.3.8. You should have the possibility again under:
Menu => All Devices => Spectrum => By animation

Please reopen if it's still not working for you.

**Comment by QuantumBytes95** [comment]
It works now! Thank you for the update!
