### ISSUE TITLE
wave effect on razer viper mini

### ISSUE THREAD

**Issue by foydass** [1kc/razer-macos#313]
hello it seems the wave effect is not working on viper mini.

**Comment by nightsky30** [comment]
Hi there,

I added support for the Viper Mini originally in the openrazer drivers. This mouse does not support the hardware based wave effect which openrazer uses with some mice and other devices. And since razer-macos is using openrazer, and doesn't support the wave effect in a software based fashion (as far as I can tell) like Synapse does with sending constant packets, there is not currently a way to add this effect for the Viper Mini. Custom effects that spam packets would need to be used with razer-macos.

Sorry, I don't own a Mac or use razer-macos. Just lurking and wanted to share some info regarding openrazer and the mouse.

**Comment by foydass** [comment]
It's ok. Thank you for taking the time!

**Comment by dhobi** [comment]
Self note to add 

featuresMissing: ["waveSimple"]

to https://github.com/1kc/razer-macos/blob/deee38844fe037fd6d43e63f08e654b07941c608/src/devices/viper_mini.json
