### ISSUE TITLE
Huntsman mini *Ripple effect 

### ISSUE THREAD

**Issue by Tochey** [1kc/razer-macos#316]
Great Job on the customization on the huntsman mini although the Ripple effect is the only that doesn't work. I hope to see more color customization added in the near future!

**Comment by dhobi** [comment]
There is an open PR which could improve/fix this:

https://github.com/1kc/razer-macos/pull/310

**Comment by dhobi** [comment]
@Tochey Does it work for you now with the latest version 0.4.0?

**Comment by Tochey** [comment]
@dhobi Ripple effect is fully working, Good job guys but I did notice some minor issues. Secondary custom color randomly switches after the Ripple (dual) effect is selected. Keyboard colors often freezes and also spasses out. These issues can be bypassed by simply unplugging your keyboard, clearing all settings and restarting the app.

**Comment by Tochey** [comment]
@dhobi Ripple effect works fine when connected to my laptop but the effect doesn't save to the onboard memory. The ripple effects also doesn't save to the current device state under state manager. When selected the starlight effects gives an error code with this latest release.
<img width="259" alt="1" src="https://user-images.githubusercontent.com/54341970/112765649-1f8f6380-8fdc-11eb-8190-0954c8f86183.png">
<img width="244" alt="2" src="https://user-images.githubusercontent.com/54341970/112765656-24ecae00-8fdc-11eb-8502-f5cbf3e1fed8.png">

**Comment by dhobi** [comment]
@Tochey 

...but the effect doesn't save to the onboard memory.
=> Unfortunately, Ripple is not a hardware effect. We have to rely on razer macOS sending single keyframes.

The ripple effects also doesn't save to the current device state under state manager.
=> Good catch! That one got lost in a merge and is fixed here now (https://github.com/1kc/razer-macos/commit/17d49d3ef0dd25eed7a0a156b3da4c3cadc37686)

starlight effects gives an error code with this latest release
=> Yes, this has been flagged here #330 as well and will be fixed in the upcoming version

Thanks for testing and flagging those bugs!

**Comment by dhobi** [comment]
@Tochey I see that @1kc just has reuploaded 0.4.0 which should contain all the fixes. Give it a try! 😃

**Comment by Tochey** [comment]
@dhobi works fine!!

**Comment by dhobi** [comment]
Great! I guess we can close this one then (Please reopen / create a new issue if you still experience some issues).
