### ISSUE TITLE
Thunderbolt Dock not recognised in 0.47

### ISSUE THREAD

**Issue by dseehof** [1kc/razer-macos#508]
Hi,

I installed 0.47 which should support the Thunderbolt dock as per the release notes, but it doesn't show up at all. Anything I can try?

Best,
Daniel

**Comment by overcurrent** [comment]
Hi, thanks for the heads up. I don't own Thunderbolt Dock and I must have totally overlooked the librazermacos submodule version in razer-macos master as the pull request related to this issue was not merged at the time I was compiling for 0.4.7.

@1kc It seems like https://github.com/1kc/librazermacos/pull/17 has been very recently merged to librazermacos master. Could you update the submodule in razer-macos so that we can get this fixed?

It might be the time to bump version to 0.4.8 very soon..

**Comment by overcurrent** [comment]
Hey, could you try this test build and see if it solves this issue: https://github.com/overcurrent/razer-macos/releases/download/v0.4.8/Razer.macOS-0.4.8-universal.dmg

Hopefully I fetched all the needed parts correctly and if it does, I'll create a pull request to upstream.

**Comment by overcurrent** [comment]
Stay tuned for the next build. I'm working to merge some other PRs first.

**Comment by dseehof** [comment]
Yup, does work for me.

**Comment by higgey123** [comment]
the preview build works for me as well. Thanks for doing this project.

**Comment by culvi** [comment]
Totally worked! Thanks so much @overcurrent
